INSERT IGNORE INTO CLIENTS(APIKEY, NAME) VALUES ('banking', 'banking');

INSERT IGNORE INTO ASSETS(CODE, NAME) VALUES ('cc', 'conta corrente');

INSERT IGNORE INTO ASSETS(CODE, NAME) VALUES ('pp', 'conta poupanca');

INSERT IGNORE INTO CURRENCY(CODE, NAME) VALUES ('BRL', 'real brasileiro');

INSERT IGNORE INTO USERS(USER_ID) VALUES ('user1');

INSERT IGNORE INTO BALANCES(USER_ID, ASSET, CURRENCY, AVAILABLE) VALUES ('user1', 'cc', 'BRL', 1000);

INSERT IGNORE INTO BALANCES(USER_ID, ASSET, CURRENCY, AVAILABLE) VALUES ('user1', 'pp', 'BRL', 1);
