CREATE TABLE IF NOT EXISTS CLIENTS
(
    ID BIGSERIAL PRIMARY KEY,
    APIKEY VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ASSETS
(
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CURRENCY
(
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGSERIAL PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS BALANCES
(
    ID BIGSERIAL PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    ASSET VARCHAR(255) NOT NULL,
    CURRENCY VARCHAR(255) NOT NULL,
    AVAILABLE DECIMAL(16, 8) DEFAULT 0,
    ON_HOLD DECIMAL(16, 8) DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (ASSET) REFERENCES ASSETS(CODE),
    FOREIGN KEY (CURRENCY) REFERENCES CURRENCY(CODE),
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS 
(
    ID BIGSERIAL PRIMARY KEY,
    HASH VARCHAR(64) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(255) NOT NULL DEFAULT 'NONE',
    CLIENT_ID BIGINT,
    PARAMS JSON,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);